Timeline/Controllers/HomeController.cs
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Timeline.Data;
using Timeline.Models;

namespace Timeline.Controllers;

public class HomeController : Controller
{
	private readonly ILogger<HomeController> _logger;
#region Variables
	private readonly DataContext _context;
#endregion

	public HomeController(ILogger<HomeController> logger, DataContext _context){
		_logger = logger;
		this._context = _context;
	}

	public async Task<IActionResult> Index(){
		var _timecontext = await _context.timeline_context.OrderBy(x=> x.timec_date).ToListAsync(); 
		return View(_timecontext);
	}

	public IActionResult Privacy(){
		return View();
	}

	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public IActionResult Error(){
		return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

Timeline/Controllers/TimelineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Timeline.Data;
using Timeline.ViewModel;

namespace Timeline.Controllers;

public class TimelineController : Controller{
#region Variables
	private readonly DataContext _context;
#endregion

#region Constructor
	public TimelineController(DataContext context){
		_context = context;
	}
#endregion

	// GET: 創建時間點
	[Authorize]
	public IActionResult CreateEvent(){
		return View(new TimePointCreateViewModel());
	}

	//POST: 創建時間點
	[HttpPost]
	[Authorize]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> CreateEvent(
		[Bind("dateTime,title,description,context,rank,dateto")] TimePointCreateViewModel _timepoint){
		if (ModelState.IsValid){
			_context.timeline_context.Add(_timepoint.CreateTimePoint());
			await _context.SaveChangesAsync();
			return RedirectToAction("Index", "Home");
		}

		return View(_timepoint);
	}
	
	// GET: User/Delete/5
	[Authorize]
	public async Task<IActionResult> Delete(string id){
		if (id == null) return NotFound();

		var _timepoint = await _context.timeline_context.FirstOrDefaultAsync(m => m.timec_id == id);

		if (_timepoint == null) return NotFound();

		return View(_timepoint);
	}

	// POST: User/Delete/5
	[HttpPost]
	[ActionName("Delete")]
	[ValidateAntiForgeryToken]
	[Authorize]
	public async Task<IActionResult> DeleteConfirmed([Bind("timec_id")]string id){
		var _timepoint = await _context.timeline_context.FindAsync(id);
		_context.timeline_context.Remove(_timepoint);
		await _context.SaveChangesAsync();
		return RedirectToAction("Index","Home");
	}
	
	public async Task<IActionResult> Details(string id){
		if (id == null) return NotFound();

		var _timepoint = await _context.timeline_context.FirstOrDefaultAsync(m => m.timec_id == id);

		if (_timepoint == null) return NotFound();

		return View(_timepoint);
	}
	
	[HttpPost]
	[ActionName("Details")]
	[ValidateAntiForgeryToken]
	[Authorize]
	public async Task<IActionResult> DetailsPost([Bind("timec_id")]string id){
		var _timepoint = await _context.timeline_context.FindAsync(id);
		_context.timeline_context.Remove(_timepoint);
		await _context.SaveChangesAsync();
		return RedirectToAction("Index","Home");
	}
	
	//檢查使用者
	private bool timepointExist(string id){
		return _context.timeline_context.Any(e => e.timec_id == id);
	}
}

Timeline/Views/Home/Index.cshtml
@model IEnumerable<Timeline.Models.timeline_context>
@{
	ViewBag.Title = "時間線產生器";
}

<div class="text-center">
	<section class="p-3">
		<h1>來製作你的時間線 &darr;</h1>
	</section>

	@if (Model!.Count() > 0){
		<section class="timeline">
			<ul class="p-3">
				@foreach (var item in Model!){
					<a class="text-reset text-decoration-none" asp-action="Details" asp-controller="Timeline" asp-route-id="@item.timec_id">
						<li>
							<div>
								@{ var _context = item.timec_date.ToString("yyyy") + "年"; }
								<time>@_context &nbsp;&nbsp; @item.timec_title</time>
								@if (item.timec_description != null){
									@item.timec_description
								}
							</div>
						</li>
					</a>
				}
			</ul>
		</section>
	}
	else{
		<section class="timeline-nopoint" id="timeline"></section>
	}
</div>

@if (User.Identity!.IsAuthenticated){
	<div class="page-right-botton" id="page-right-botton">
		<a class="border-0 text-reset" asp-action="CreateEvent" asp-controller="Timeline">
			<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
				<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
			</svg>
		</a>
	</div>
}